### ISSUE TITLE
Consrv 👍  this could be the go-to tool that can re-define how serial console's could be accessed

### ISSUE THREAD

**Issue by ksingh7** [mdlayher/consrv#7]
Hi @stapelberg  / @mdlayher 

Let me start with this, "This project solves a real problem" of making serial connection accessible over SSH. 
I can see a lot of use cases where this project could bring a lot of value for ex : 
1) Getting console access of network switches/firewalls for remote (over the internet) management (and trust me there are millions of such devices on the ground)
2) Getting console access of servers (over the internet) think about edge computing where we do not have a datacenter, just have one machine lying in the toll plaza etc. Management of those devices over the internet could be a boon.
3) And don't forget IoT devices etc

I am very much interested to contribute to this project (i have just started to learn go) but i can at least contribute in testing this end-to-end , writing documentation/blogs/videos (if that is considered as contribution 👯 )

Before i can do the above, i need to setup a homelab and try out consrv , based on my experience i will test this and document my journey in blogs/readme/examples etc. 

Is there a slack/irc/discord group where you guys hangout, i would like to join that and be a part of this journey.

**Comment by stapelberg** [comment]
Hey @ksingh7 

I’m glad you are excited by this project!

That said, please note that consrv is a hobby project that pretty much does what we need, so there’s no slack, irc or discord, no roadmap, and no exciting journey, or really plans to do much development at all :)

For corporate use, a commercially supported product will be preferable and often even required. Hence, I don’t think consrv will change the market much.

> I am very much interested to contribute to this project (i have just started to learn go) but i can at least contribute in testing this end-to-end , writing documentation/blogs/videos (if that is considered as contribution dancers )

Sure, you’re definitely welcome to publish blog posts and such!

> Do you know if consrv CLI could be worked on Windows machine i.e

The underlying Go package we use for accessing the serial console (`github.com/tarm/serial`) does have an implementation for Windows, but I have never tested it. You’d need to experiment and see for yourself.

> Currrently consrv is a CLI tool that needs to be run on a RPI host, do you guys have plan to release this as a go package ? I think this could definitely increase the adoption of consrv as an embedded package that other go utilities could leverage? what do you think ?

I don’t know whether consrv really is that useful to embed. Typically, you want to run one service for one logical function, and consrv is that service. Can you give some examples of what sort of programs would embed consrv?

**Comment by mdlayher** [comment]
Pretty much what Michael said. Closing, thanks for your interest!
